### ISSUE TITLE
kolnovel domain changed

### ISSUE THREAD

**Issue by kiraoussama** [LNReader/lnreader-plugins#1004] opened 2024-06-25 21:47 UTC
### Source information

Kolnovel ملوك الروايات

### Steps to reproduce

kolnovel domain changed

### Expected behavior

domain not same

### Actual behavior

the right domain

### LNReader version

Stable 2.0.0

### Android version

Android 14

### Other details

nothing really

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-06-26 09:07
Duplicate of #1001

**Closed by rajarsheechatterjee** 2024-06-26 09:07 UTC
Labels: Bug
