### ISSUE TITLE
text doesn't appear in chapters

### ISSUE THREAD

**Issue by mohamedku53** [LNReader/lnreader-plugins#1303] opened 2024-11-07 12:10 UTC
### Source information

novelbin

### Steps to reproduce

open how a realist hero rebuilt the kingdom book 9 chapter 7

### Expected behavior

Text should appear

### Actual behavior

it says if the text appears in the webveiw i should report

### LNReader version

1.20 beta

### Android version

8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedku53** [comment] 2024-11-07 12:43
release 2.0.0 beta*

**Comment by error7404** [comment] 2024-11-07 17:00
Duplicate of #1244 & #1289

**Closed** 2024-11-16 07:18 UTC
Labels: Bug
