### ISSUE TITLE
Wiebview

### ISSUE THREAD

**Issue by Dhanarcihuyy** [LNReader/lnreader-plugins#1166] opened 2024-08-25 13:42 UTC
### Source information

Sakura novel

### Steps to reproduce

No text at all

### Expected behavior

Please fix it

### Actual behavior

Please fix it 

### LNReader version

2.0.0

### Android version

Android 11

### Other details

Please fix it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-08-25 18:00
Duplicate of #891

**Closed** 2024-08-27 08:06 UTC
Labels: Bug, Duplicate
