### ISSUE TITLE
Pls fix kolnovel  source 

### ISSUE THREAD

**Issue by Medaminnnn** [LNReader/lnreader-plugins#1227] opened 2024-10-18 10:49 UTC
### Source information

Kolnovel

### Steps to reproduce

Idk

### Expected behavior

The website changed their site so pls change the sources 

### Actual behavior

Pls

### LNReader version

Latest version 

### Android version

Android 14

### Other details

Pls

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-10-18 12:18
Duplicate of #1226 

Please avoid creating duplicate issues.

**Closed by rajarsheechatterjee** 2024-10-18 12:18 UTC
Labels: Bug
