### ISSUE TITLE
SakuraNovel blank chapter

### ISSUE THREAD

**Issue by lorzd** [LNReader/lnreader-plugins#1321] opened 2024-11-15 03:02 UTC
### Source information

SakuraNovel

### Steps to reproduce

1. Open sakuranovel 2. Open first chapter 3.open other chapter 4. All chapter blanks

### Expected behavior

It's should be

![Screenshot_2024-11-15-10-00-31-086_com rajarsheechatterjee LNReader-edit](https://github.com/user-attachments/assets/51f54981-3906-476e-9356-961a9bbaaa62)

### Actual behavior

This happen instead

![Screenshot_2024-11-15-10-01-21-189_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/4c484b55-6316-4c45-b662-48b1e9ca6c47)

### LNReader version

2.0.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-11-15 07:05
Duplicate of #891

**Closed by error7404** 2024-11-15 07:05 UTC
Labels: Bug
