### ISSUE TITLE
It's a good site

### ISSUE THREAD

**Issue by shadow12364** [LNReader/lnreader-plugins#949] opened 2024-05-24 12:19 UTC
### Source name

Novels Paradise

### Source link

https://novelsparadise.site/

### Language

Arabic 

### Other details

. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-05-26 08:24
Duplicate of #564

**Comment by nyagami** [comment] 2024-05-26 10:26
the source was added in 2.0 version, you can try the beta release or wait for its stable

**Closed by nyagami** 2024-05-26 10:26 UTC
Labels: Source Request
