### ISSUE TITLE
Novelupdates Double Chapters

### ISSUE THREAD

**Issue by Ma-kuu** [LNReader/lnreader-plugins#1203] opened 2024-09-26 23:09 UTC
### Source information

Novelupdates

### Steps to reproduce

1. Save a novel from novelupdates
2. Update through updates tab
3. Check the chapter list of the novel
4. Done
![Screenshot_20240927_070407_LNReader](https://github.com/user-attachments/assets/342144dd-c1b6-4082-bc94-ce36dce9d01e)
![Screenshot_20240927_070411_LNReader](https://github.com/user-attachments/assets/fcc5869f-9b68-4edf-9cc2-d2e6b3f2b1a1)

### Expected behavior

Chapters will not double if the library is updated

### Actual behavior

When Updating the library, chapters from  the novles of novelupdates will double, sometimes it Doesn’t happen.

### LNReader version

2.0.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-09-26 23:33
Duplicate of #1185

**Closed** 2024-09-27 05:22 UTC
Labels: Bug
