### ISSUE TITLE
Problem no writing in chapte

### ISSUE THREAD

**Issue by Kayan877** [LNReader/lnreader-plugins#1201] opened 2024-09-25 23:57 UTC
### Source information

Sakuranovel.id

### Steps to reproduce

![Screenshot_20240925-204943_LNReader](https://github.com/user-attachments/assets/9e5db9ad-5e26-43cd-873a-cfe7de49323c)

### Expected behavior

There should be a writing in that chapter

### Actual behavior

Instead it doesn't display anything

### LNReader version

2.0.0.beta 2

### Android version

Android 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-09-26 08:38
Duplicate of #891

**Comment by Kayan877** [comment] 2024-09-26 14:07
> Duplikat #891

So that's from the website itself

**Closed** 2024-09-27 05:23 UTC
Labels: Bug
