### ISSUE TITLE
add mtl genres

### ISSUE THREAD

**Issue by WGmg23** [LNReader/lnreader-plugins#1071] opened 2024-07-18 20:14 UTC
![Screenshot_2024-07-18-16-11-22-975_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/265dab79-0201-4caf-914b-d2c39cdff73a)

### Source name

mtlnovel, mtlnoveles

### Source link

mtlnovels.com

### Language

English Spanish 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-07-18 21:21
it's already in the app, you need to download the latest beta
done in #1023
duplicate of #1010

**Closed** 2024-07-19 06:47 UTC
Labels: Source Request

**Comment by WGmg23** [comment] 2024-07-20 21:37
no
![Screenshot_2024-07-21-03-06-29-265_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/5a61c9a3-d7dd-40a4-8f2b-d784a7d3e4f3)


> it's already in the app, you need to download the latest beta done in #1023 duplicate of #1010

**Comment by error7404** [comment] 2024-07-20 21:45
It's not a filter it's another source
