### ISSUE TITLE
Kolnovel new domain

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-plugins#1015] opened 2024-06-30 08:02 UTC
### Source information

Kolnovel 

### Steps to reproduce

Kolnovel changed their domain

### Expected behavior

Domain changed 

### Actual behavior

No results found 

### LNReader version

2.0.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-06-30 08:04
Duplicate of #1001

**Closed** 2024-06-30 08:04 UTC
Labels: Bug, Duplicate

**Comment by Mingo3347** [comment] 2024-07-01 10:27
Oh I know this was a duplicate, I was just wondering if the source will get fixed soon or is there a problem with it. Sent from my Galaxy
-------- Original message --------From: "github-actions[bot]" ***@***.***> Date: 6/30/24  11:05 AM  (GMT+02:00) To: LNReader/lnreader-plugins ***@***.***> Cc: Mingo3347 ***@***.***>, Author ***@***.***> Subject: Re: [LNReader/lnreader-plugins] Kolnovel new domain (Issue #1015) 
Closed #1015 as not planned.
