### ISSUE TITLE
Unable to open Foxaholic chapters

### ISSUE THREAD

**Issue by yuu1412** [LNReader/lnreader-plugins#737] opened 2024-01-29 00:36 UTC
### Source information

Foxaholic (ID: 22)

### Steps to reproduce

1. Open a novel hosted on Foxaholic
2. Click chapter to read
3. Receive "The app couldn't bypass the source's CloudFlare protection." error
4. Click web view button
5. Complete CloudFlare protection
6. Press Retry
7. Get a white screen saying: "Error loading page | Domain: undefined | Error Code: -2 | Description: net::ERR_NAME_NOT_RESOLVED"

### Expected behavior

Chapter opens to be read 

### Actual behavior

Receive ERR_NAME_NOT_RESOLVED error

### LNReader version

1.1.19

### Android version

Android 13

### Other details

Reporting for a friend. On my own device (running 1.1.19 on Android 14), I have not replicated this bug.

She has the same error trying to open other novels hosted on Foxaholic. This error does not occur when reading on other sources (i.e. NovelBuddy)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment] 2024-02-07 17:58
Unable to reproduce. Novel Name?
![image](https://github.com/LNReader/lnreader-sources/assets/26593485/46dd4b75-1c30-41b8-9f46-50f825c1f2e7)
![image](https://github.com/LNReader/lnreader-sources/assets/26593485/e6ccdeda-3cc6-49b3-8831-fa5691b2e473)

**Comment by yuu1412** [comment] 2024-02-07 18:28
I became the lousy side top

**Comment by error7404** [comment] 2024-03-18 21:44
seems fixed in beta
[LNReader/lnreader/releases/v2.0.0-beta.0](https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.0)
make sure to convert your backup

**Comment by yuu1412** [comment] 2024-03-18 21:54
Thanks!

**Comment by nyagami** [comment] 2024-04-28 04:10
You can try v2 beta or wait for it stable release

**Closed by nyagami** 2024-04-28 04:10 UTC
Labels: Bug
