### ISSUE TITLE
Chapters are empty

### ISSUE THREAD

**Issue by x7sony** [LNReader/lnreader-plugins#923] opened 2024-05-02 15:47 UTC
### Source information

Riwyat - arabic section

### Steps to reproduce

Open the novel (shadow slave)
Press the chapter
And it says it's empty

### Expected behavior

It should open normally with words in it

### Actual behavior

It says it's empty

### LNReader version

1.1.19

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-05-02 16:56
Duplicate of #896

**Closed** 2024-08-06 09:11 UTC
Labels: Bug
