### ISSUE TITLE
Full novel

### ISSUE THREAD

**Issue by NKJibu02** [LNReader/lnreader-plugins#1142] opened 2024-08-14 14:08 UTC
### Source name

Fullnovel

### Source link

Fullnovel.com

### Language

English

### Other details

Source request for adding full novel site

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-08-14 14:20
https://fullnovel.com doesn't exist, are you sure this is the right URL?

**Comment by error7404** [comment] 2024-08-14 14:32
duplicate of #585

**Closed** 2024-08-14 14:56 UTC
Labels: Source Request
