### ISSUE TITLE
Blank/Black Cover NovelUpdates

### ISSUE THREAD

**Issue by Chris-Boho** [LNReader/lnreader-plugins#730] opened 2024-01-26 16:55 UTC
### Source information

Novel Updates

### Steps to reproduce

1. Log in to Novel Updates
2. Update library
3. Covers turn black/empty
4. This only happens if you are logged into novelupdates and the update meta data option is enabled in settings.

### Expected behavior

Covers in the app should show the covers on the novel updates page.

### Actual behavior

Cover turns blank / black on update.

### LNReader version

1.1.18

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.18](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Sakya22** [comment] 2024-01-26 17:44
Hey. Your issue is a duplicate of my issue and my issue got updated as fixed so this fix should be available next update. My issue number is #878 in the LNReader repo.

**Comment by rajarsheechatterjee** [comment] 2024-04-14 03:42
Closing this since it should be resolved in _v1.1.19_.

**Closed by rajarsheechatterjee** 2024-04-14 03:42 UTC
Labels: Bug
