### ISSUE TITLE
Domain change 

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-plugins#1005] opened 2024-06-26 04:27 UTC
### Source information

Kolnovel (ملوك الروايات)

### Steps to reproduce

Just click on the source and the you will find it saying no results.
Open the web view and it will show a screen with a redirecting link to the new website domain 
![Screenshot_20240626-072720_LNReader](https://github.com/LNReader/lnreader-plugins/assets/108782331/0b0fec72-dbf2-49f5-a812-b4cc9a9cc4c7)

### Expected behavior

A working source 

### Actual behavior

No results  found 
![Screenshot_20240626-072649_LNReader](https://github.com/LNReader/lnreader-plugins/assets/108782331/4c03f2c7-284d-4120-a6e5-b237024cf68f)

### LNReader version

2.0.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-06-26 09:08
Duplicate of #1001

**Closed by rajarsheechatterjee** 2024-06-26 09:08 UTC
Labels: Bug
