### ISSUE TITLE
Novel bin is not showing entries 

### ISSUE THREAD

**Issue by ChaosReturn** [LNReader/lnreader-plugins#1213] opened 2024-10-07 17:18 UTC
### Source information

Novel bin

### Steps to reproduce

Step 1: Open novel bin 
Step 2: open any novel
Issue: no novel name and chapters are displayed 

### Expected behavior

Novel name and chapters are displayed 

### Actual behavior

No novel name and chapters are displayed 

### LNReader version

2.0.0 bete 2

### Android version

Android 12 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-10-07 17:20
Duplicate of https://github.com/LNReader/lnreader-plugins/issues/1199

Why did you create a separate issue when there's already an existing one that you're aware of, as you've commented on it?

**Closed by rajarsheechatterjee** 2024-10-07 17:20 UTC
Labels: Bug

**Comment by ChaosReturn** [comment] 2024-10-07 17:29
The issue is not being resolved and the issue had started before 2 weeks

**Comment by rajarsheechatterjee** [comment] 2024-10-07 18:48
If the issue is still open, that means it hasn't been resolved yet. Creating duplicate issues doesn't help; it just adds unnecessary spam.
