### ISSUE TITLE
Problem opening one of the sources

### ISSUE THREAD

**Issue by Ahmedz10** [LNReader/lnreader-plugins#1179] opened 2024-09-05 06:52 UTC
### Source information

novelsparadise

### Steps to reproduce

When I open this source it gives this result novelsparadise
It does not work and it asks me to open it in the application's browser, and when I open it it says that it is forbidden to open the site in this browser

### Expected behavior

The site should open

### Actual behavior

Could not reach site (403) try to open in webview.
When l use webview it gives me this result 
![Uploading Screenshot_20240905_084032_com.rajarsheechatterjee.LNReader.jpg…]()

### LNReader version

V2.0.0

### Android version

Android 10

### Other details

![Screenshot_20240905_084032_com rajarsheechatterjee LNReader](https://github.com/user-attachments/assets/734d7669-6b2a-4b94-b6ac-ecee56c23c09)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-09-05 09:30
duplicate of #1101

**Closed** 2024-09-05 13:41 UTC
Labels: Bug, Duplicate
