### ISSUE TITLE
Add this source "CPU Novel", it is much needed

### ISSUE THREAD

**Issue by N-U-ser** [LNReader/lnreader-plugins#1222] opened 2024-10-13 07:38 UTC
### Source name

CPU Novel

### Source link

https://cpunovel.com

### Language

English,Korean

### Other details

It has raws in korean and a small menu at bottom from which you can select the language you want it to translate it to. It is a MTL (machine-translate) site, but it is the only site which has 700 chapters of 'Surviving the Game as a Barbarian' ,of which famous manhwa of the same name an adaptation of, while other sites stopped at 300 chaps. It updates/adds novels(chapters) regularly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a title with source name.
- [ ] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/LNReader/lnreader/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-10-13 08:27
Duplicate of #935
Please update the app to beta 2.0

**Closed** 2024-10-13 09:13 UTC
Labels: Source Request

**Comment by N-U-ser** [comment] 2024-10-13 09:15
It seems the issue was already there ,Named as " New Domain name".

**Comment by error7404** [comment] 2024-10-13 10:03
You could just check in the app

**Comment by N-U-ser** [comment] 2024-10-13 10:25
**Ok. Sorry about that. What i had a problem in general (having a hard time with), is confirming if any kind of "issue" is not already open/posted , just wish that github was bit more user-friendly towards users/testers who are not as knowledgeable about as developers.**
### Please help me with this. I just updated to beta 2.0.
**I made a backup before updating in hopes atleast library would be restored if not history, it didn't restore. Then i made the `migrated-backup.json` file and tried to restore. It didn't work either. Nothing happens when using the `Restore` option.

**_Install permissions has been given And Plugin repository has been added_**

**Is there Something that i missed? Is the Restore option Non-functional for this beta version and will be worked upon on next update? Because even migrated-backup doesn't seem to work. Please tell me what to do.**

**Comment by error7404** [comment] 2024-10-13 10:33
have you bypassed Cloudflare / logged into sites (for NU)?
if so upload your backup on the [support channel](https://discord.com/channels/835746409357246465/835757769172713503) for further help
https://discord.gg/QdcWN4MD63

**Comment by N-U-ser** [comment] 2024-10-13 12:11
### Issue got solved
**When i manually added/installed extension before restoring then entries of installed plugins showed up. It doesn't restores or creates entries in library until relevant plugin are manually installed/added unlike other Tachiyomi-based apps which do one click restore.**
