### ISSUE TITLE
NovelsKnight bugged

### ISSUE THREAD

**Issue by B3H3M0T** [LNReader/lnreader-plugins#1195] opened 2024-09-22 18:30 UTC
### Source information

novelsknight.com

### Steps to reproduce

Open plugin it will error the cause was captcha and said to open webview but nothing happen.

### Expected behavior

It load normaly

### Actual behavior

It wont load

### LNReader version

V2 beta 2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-09-22 19:42
Duplicate of #1039

**Closed** 2024-09-27 05:23 UTC
Labels: Bug
