### ISSUE TITLE
Source renewal

### ISSUE THREAD

**Issue by dd5gl** [LNReader/lnreader-plugins#976] opened 2024-06-06 22:35 UTC
### Source information

kolnovel.clup

### Steps to reproduce

1- open source 
2- nothing
3- open WebView 
4- also nothing

bc the site has been changed to
https://kolnovel.club/

### Expected behavior

It is assumed that the new forum site exists instead of the old one

### Actual behavior

Nothing appears, and chapters don't work

### LNReader version

2.0.0

### Android version

14 android 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-06-07 04:20
Duplicate of #957
Fixed in #948 and #920

Please update kolnovel plugin to version 1.1.1 or greater (slide left on the plugin and press the update button)

**Comment by error7404** [comment] 2024-06-09 17:36
Is it not fixed?

**Comment by rajarsheechatterjee** [comment] 2024-07-19 07:41
Resolved in commit 4bd7df1d61c84b26e3ce3b847b432b13430c0570

**Closed by rajarsheechatterjee** 2024-07-19 07:41 UTC
Labels: Bug
