### ISSUE TITLE
Chapters show an Webvirw but not in app

### ISSUE THREAD

**Issue by piunit1** [LNReader/lnreader-plugins#1253] opened 2024-10-29 19:42 UTC
### Source information

https://novelbin.me/novel-book/awakeningthe-infinite-evolution-of-my-talent-as-a-low-level-awakener

### Steps to reproduce

Starting from chapter 2 it wont show the chapter even tho you can read it on webview

### Expected behavior

The full chapter

### Actual behavior

Error report to post it on github

### LNReader version

1.1.19

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-10-30 02:13
Duplicate of https://github.com/LNReader/lnreader-plugins/issues/1244

**Closed by rajarsheechatterjee** 2024-10-30 02:13 UTC
Labels: Bug
