### ISSUE TITLE
novel Paradise : You have been banned.

### ISSUE THREAD

**Issue by OtakuArab** [LNReader/lnreader-plugins#1153] opened 2024-08-20 21:16 UTC
### Source information

novel paradise

### Steps to reproduce

Access to the resource - 403 link error - Bypass attempt - You have been blocked

### Expected behavior

Must appear or exceed

### Actual behavior

But it does not exceed the banned when browsing

### LNReader version

2.0

### Android version

Android 12 

### Other details

![Screenshot_٢٠٢٤٠٨٢١-٠٠١٠٣٨_LNReader](https://github.com/user-attachments/assets/8d86da46-750c-4fef-bac7-a8fdb5a05086)
![Screenshot_٢٠٢٤٠٨٢١-٠٠١٤٥٠_LNReader](https://github.com/user-attachments/assets/827fdaa8-8cee-427b-b73f-fa7dded6c77d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by error7404** [comment] 2024-08-20 22:46
duplicate of #1101

**Closed** 2024-08-21 07:39 UTC
Labels: Bug, Duplicate
