### ISSUE TITLE
Kolnovel new domain

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-plugins#1020] opened 2024-07-01 15:25 UTC
### Source information

Kolnovel 

### Steps to reproduce

Kolnovel changed their domain

### Expected behavior

Domain changed 

### Actual behavior

No results found 

### LNReader version

2.0.0

### Android version

Android 11

### Other details

New domain 

https://kolbook.xyz/

P.s: would really appreciate if it's fixed soon as it's been a week since one of the only good Arabic sources been down.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by rajarsheechatterjee** [comment] 2024-07-01 15:37
Duplicate of #1001

Why create the same issue every day when it has already been closed as a duplicate? Reposting the issue will not help in getting it fixed.

**Closed by rajarsheechatterjee** 2024-07-01 15:37 UTC
Labels: Bug

**Comment by Mingo3347** [comment] 2024-07-01 15:52
My apologize.Sent from my Galaxy
