### ISSUE TITLE
KolNovel: Unrelated Paragraphs

### ISSUE THREAD

**Issue by Mingo3347** [LNReader/lnreader-plugins#534] opened 2023-07-07 15:28 UTC
### Source information

KolNovel

### Steps to reproduce

Example 
1: go to any light novel 
2:open any chapter 
3: between every paragraph there's unrelated information from the light novel, like it's some ads 

### Expected behavior

The content of the chapter is supposed to belong to the light novel that I'm reading 

### Actual behavior

Unrelated content between every paragraph which makes reading impossible to do

### LNReader version

1.1.15

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.15](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by K1ngfish3r** [comment] 2023-07-09 08:08
duplicate of https://github.com/LNReader/lnreader-sources/issues/521

> This has been fixed for the next release, you may obtain a debug version here > https://github.com/LNReader/lnreader/actions/runs/5286111701

If this didn't fix it, let us know thanks

**Comment by K1ngfish3r** [comment] 2023-09-17 15:43
apparently, my fix missed the 1.1.17 release window, big oof
![image](https://github.com/LNReader/lnreader-sources/assets/26593485/24f38719-69b8-41ae-8184-8f1f0c60d3fb)
you may still use the debug version to fix this issue

**Closed** 2024-04-28 04:01 UTC
Labels: Bug
